server:
  port: 9003
spring:
  application:
    name: goods
  profiles:
    include:
      comm
# 注册中心配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${wxshop.eureka.port}/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
